# Generated by Django 5.2 on 2026-07-03 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_tarea_is_manually_blocked_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("branch_name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "last_commit_sha",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("last_commit_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_branches",
                        to="core.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Branch",
                "verbose_name_plural": "GitHub Branches",
                "ordering": ["branch_name"],
            },
        ),
        migrations.CreateModel(
            name="GitHubCommit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField()),
                ("author_login", models.CharField(max_length=100)),
                ("author_avatar", models.URLField(blank=True, default="")),
                ("committed_at", models.DateTimeField()),
                ("is_fix", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.area",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github_sync.githubbranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Commit",
                "verbose_name_plural": "GitHub Commits",
                "ordering": ["-committed_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("repo_owner", models.CharField(max_length=100)),
                ("repo_name", models.CharField(max_length=100)),
                ("access_token_encrypted", models.TextField()),
                (
                    "webhook_secret",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("webhook_id", models.IntegerField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_connection",
                        to="core.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Connection",
                "verbose_name_plural": "GitHub Connections",
            },
        ),
        migrations.AddField(
            model_name="githubbranch",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="github_sync.githubconnection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="githubbranch",
            unique_together={("connection", "branch_name")},
        ),
        migrations.CreateModel(
            name="GitHubAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("dependabot", "Dependabot"),
                            ("code_scanning", "Code Scanning"),
                            ("secret_scanning", "Secret Scanning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("warning", "Warning"),
                            ("note", "Note"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "package_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("html_url", models.URLField()),
                ("github_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="github_sync.githubconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Alert",
                "verbose_name_plural": "GitHub Alerts",
                "ordering": ["-created_at"],
                "unique_together": {("connection", "alert_type", "github_id")},
            },
        ),
    ]
