# Generated by Django 5.0.14 on 2026-07-02 19:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flujo_estados', models.JSONField(default=list, help_text="Custom flow states, e.g. ['backlog','desarrollo','revision_legal','qa','done']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('orden', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('meet_link', models.URLField(blank=True, default='')),
                ('meet_titulo', models.CharField(blank=True, default='', max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='core.proyecto')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=512)),
                ('responsable_nombre', models.CharField(blank=True, default='', help_text='Raw name from Excel before user matching', max_length=255)),
                ('especificaciones_tecnicas', models.TextField(blank=True, default='')),
                ('criterios_aceptacion', models.JSONField(default=list, help_text='List of {text, done} objects')),
                ('participantes_data', models.JSONField(blank=True, default=dict, help_text='Raw participant info from Excel')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('desarrollo', 'Desarrollo'), ('revision_legal', 'Revisión Legal'), ('qa', 'QA'), ('done', 'Done')], default='backlog', max_length=20)),
                ('fecha_inicio_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='core.area')),
                ('dependencias', models.ManyToManyField(blank=True, help_text='Tasks that must be DONE before this one can start', to='core.tarea')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.sprint')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['sprint__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('meet_link', models.URLField()),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.sprint')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.tarea')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
