# Generated by Django 5.2 on 2026-07-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tarea_is_manually_blocked_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="complejidad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("media", "Media"),
                    ("alta", "Alta"),
                    ("extrema", "Extrema"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="completitud_pct",
            field=models.IntegerField(
                default=0, help_text="0-100 percentage from Excel"
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="estado_excel",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_progreso", "En Progreso"),
                    ("completado", "Completado"),
                    ("bloqueado", "Bloqueado"),
                ],
                default="pendiente",
                help_text="Tracking status from Excel (separate from workflow status)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tarea",
            name="evidencia_codigo",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="tarea",
            name="rama_github",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tarea",
            name="riesgo_mitigacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tarea",
            name="stack_especifico",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="tarea",
            name="tipo_tarea",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("fullstack", "Fullstack"),
                    ("devops", "DevOps/Arquitectura"),
                    ("gestion", "Gestion"),
                    ("diseno", "Diseno"),
                    ("otros", "Otros"),
                ],
                default="otros",
                help_text="Backend, Frontend, Fullstack, DevOps, Gestion, Diseno",
                max_length=20,
            ),
        ),
    ]
