# Generated by Django 5.2 on 2026-07-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tarea_complejidad_tarea_completitud_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False, help_text="Force password change on next login"
            ),
        ),
    ]
